name: ros_foxglove_bridge
 
services:
  ros_foxglove_bridge:
    container_name: ros_foxglove_bridge
    build:
      context: .
      dockerfile: Dockerfile.ros2
    volumes:
      - ./foxglove_bridge_base:/ros2_ws/src/ros-foxglove-bridge/foxglove_bridge_base
      - ./ros2_foxglove_bridge:/ros2_ws/src/ros-foxglove-bridge/ros2_foxglove_bridge
    privileged: true
    ipc: host
    network_mode: host
    command: "tail -f /dev/null"
    environment:
      - ROS_DOMAIN_ID=123
 
