name: CI

on:
  push:
    branches: [main, release/*]
  pull_request:

jobs:
  lint:
    strategy:
      fail-fast: false

    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: jpribyl/action-docker-layer-caching@v0.1.0
        continue-on-error: true
      - run: make lint

  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - ros_distribution: melodic
          - ros_distribution: noetic
          - ros_distribution: galactic
          - ros_distribution: humble
          - ros_distribution: rolling

    name: Test (ROS ${{ matrix.ros_distribution }})
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: jpribyl/action-docker-layer-caching@v0.1.0
        continue-on-error: true
      - run: make ${{ matrix.ros_distribution }}-test
