name: CI

on:
  push:
    branches: [main, release/*]
  pull_request:

jobs:
  lint:
    strategy:
      fail-fast: false

    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: make lint

  test:
    strategy:
      fail-fast: false
      matrix:
        ros_distribution: [melodic, noetic, humble, iron, jazzy, kilted, rolling]

    name: Test (ROS ${{ matrix.ros_distribution }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make ${{ matrix.ros_distribution }}-test

  test-boost-asio:
    strategy:
      fail-fast: false
      matrix:
        ros_distribution: [noetic, humble, rolling]

    name: Test (ROS ${{ matrix.ros_distribution }}, Boost Asio)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make ${{ matrix.ros_distribution }}-test-boost-asio

  test-sdk:
    strategy:
      fail-fast: false
      matrix:
        ros_distribution: [jazzy, kilted, rolling]

    name: Test (ROS ${{ matrix.ros_distribution }}, SDK Server)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - run: make USE_FOXGLOVE_SDK=ON ${{ matrix.ros_distribution }}-test
