name: CI

on:
  push:
    branches: [main, release/*]
  pull_request:

jobs:
  lint:
    strategy:
      fail-fast: false

    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: make lint

  test:
    strategy:
      fail-fast: false
      matrix:
        distro: [melodic, noetic, galactic, humble, iron, rolling]
        asio: [standalone, boost]

    name: Test (ROS ${{ matrix.ros_distribution }}-${{ matrix.ros_distribution }}-asio)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: make ${{ matrix.ros_distribution }}-test-${{ matrix.ros_distribution }}-asio
