name: Publish

on:
  push:
    branches: [main]

jobs:
  docker:
    strategy:
      matrix:
        ros: ["melodic", "noetic", "foxy", "galactic", "humble", "rolling"]

    name: Publish ROS ${{ matrix.ros }} container to GHCR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker tags
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/foxglove/foxglove_bridge-${{ matrix.ros }}
          tags: |
            latest

      - name: Configure QEMU
        uses: docker/setup-qemu-action@v2

      - name: Configure Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile.ros${{ fromJSON('["2", "1"]')[contains(fromJson('["melodic", "noetic"]'), matrix.ros)] }}
          build-args: |
            ROS_DISTRIBUTION=${{ matrix.ros }}
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
