name: Publish

on:
  push:
    branches: [main]

jobs:
  docker-ros1:
    strategy:
      fail-fast: false
      matrix:
        ros: ["melodic", "noetic"]

    name: Publish ROS 1 ${{ matrix.ros }} container to GHCR
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker tags
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/foxglove/${{ matrix.ros }}-ros1-bridge
          tags: |
            latest

      - name: Configure QEMU
        uses: docker/setup-qemu-action@v2

      - name: Configure Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile.ros1
          build-args: |
            ROS_DISTRIBUTION=${{ matrix.ros }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  docker-ros2:
    strategy:
      fail-fast: false
      matrix:
        ros: ["galactic", "humble", "rolling"]

    name: Publish ROS 2 ${{ matrix.ros }} container to GHCR
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker tags
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/foxglove/${{ matrix.ros }}-ros2-bridge
          tags: |
            latest

      - name: Configure QEMU
        uses: docker/setup-qemu-action@v2

      - name: Configure Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile.ros2
          build-args: |
            ROS_DISTRIBUTION=${{ matrix.ros }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
